const keycodes = {
  letters: [
    { code: 'KC_A', aliases: [], desc: 'a and A' },
    { code: 'KC_B', aliases: [], desc: 'b and B' },
    { code: 'KC_C', aliases: [], desc: 'c and C' },
    { code: 'KC_D', aliases: [], desc: 'd and D' },
    { code: 'KC_E', aliases: [], desc: 'e and E' },
    { code: 'KC_F', aliases: [], desc: 'f and F' },
    { code: 'KC_G', aliases: [], desc: 'g and G' },
    { code: 'KC_H', aliases: [], desc: 'h and H' },
    { code: 'KC_I', aliases: [], desc: 'i and I' },
    { code: 'KC_J', aliases: [], desc: 'j and J' },
    { code: 'KC_K', aliases: [], desc: 'k and K' },
    { code: 'KC_L', aliases: [], desc: 'l and L' },
    { code: 'KC_M', aliases: [], desc: 'm and M' },
    { code: 'KC_N', aliases: [], desc: 'n and N' },
    { code: 'KC_O', aliases: [], desc: 'o and O' },
    { code: 'KC_P', aliases: [], desc: 'p and P' },
    { code: 'KC_Q', aliases: [], desc: 'q and Q' },
    { code: 'KC_R', aliases: [], desc: 'r and R' },
    { code: 'KC_S', aliases: [], desc: 's and S' },
    { code: 'KC_T', aliases: [], desc: 't and T' },
    { code: 'KC_U', aliases: [], desc: 'u and U' },
    { code: 'KC_V', aliases: [], desc: 'v and V' },
    { code: 'KC_W', aliases: [], desc: 'w and W' },
    { code: 'KC_X', aliases: [], desc: 'x and X' },
    { code: 'KC_Y', aliases: [], desc: 'y and Y' },
    { code: 'KC_Z', aliases: [], desc: 'z and Z' },
    { code: 'KC_1', aliases: [], desc: '1 and !' },
    { code: 'KC_2', aliases: [], desc: '2 and @' },
    { code: 'KC_3', aliases: [], desc: '3 and #' },
    { code: 'KC_4', aliases: [], desc: '4 and $' },
    { code: 'KC_5', aliases: [], desc: '5 and %' },
    { code: 'KC_6', aliases: [], desc: '6 and ^' },
    { code: 'KC_7', aliases: [], desc: '7 and &' },
    { code: 'KC_8', aliases: [], desc: '8 and *' },
    { code: 'KC_9', aliases: [], desc: '9 and (' },
    { code: 'KC_0', aliases: [], desc: '0 and )' }
  ],
  fkeys: [
    { code: 'KC_F1', aliases: [], desc: 'F1' },
    { code: 'KC_F2', aliases: [], desc: 'F2' },
    { code: 'KC_F3', aliases: [], desc: 'F3' },
    { code: 'KC_F4', aliases: [], desc: 'F4' },
    { code: 'KC_F5', aliases: [], desc: 'F5' },
    { code: 'KC_F6', aliases: [], desc: 'F6' },
    { code: 'KC_F7', aliases: [], desc: 'F7' },
    { code: 'KC_F8', aliases: [], desc: 'F8' },
    { code: 'KC_F9', aliases: [], desc: 'F9' },
    { code: 'KC_F10', aliases: [], desc: 'F10' },
    { code: 'KC_F11', aliases: [], desc: 'F11' },
    { code: 'KC_F12', aliases: [], desc: 'F12' },
    { code: 'KC_F13', aliases: [], desc: 'F13' },
    { code: 'KC_F14', aliases: [], desc: 'F14' },
    { code: 'KC_F15', aliases: [], desc: 'F15' },
    { code: 'KC_F16', aliases: [], desc: 'F16' },
    { code: 'KC_F17', aliases: [], desc: 'F17' },
    { code: 'KC_F18', aliases: [], desc: 'F18' },
    { code: 'KC_F19', aliases: [], desc: 'F19' },
    { code: 'KC_F20', aliases: [], desc: 'F20' },
    { code: 'KC_F21', aliases: [], desc: 'F21' },
    { code: 'KC_F22', aliases: [], desc: 'F22' },
    { code: 'KC_F23', aliases: [], desc: 'F23' },
    { code: 'KC_F24', aliases: [], desc: 'F24' }
  ],
  punctuation: [
    { code: 'KC_ENTER', aliases: ['KC_ENT'], desc: 'Return (Enter)' },
    { code: 'KC_ESCAPE', aliases: ['KC_ESC'], desc: 'Escape' },
    { code: 'KC_BACKSPACE', aliases: ['KC_BSPC'], desc: 'Delete (Backspace)' },
    { code: 'KC_TAB', aliases: [], desc: 'Tab' },
    { code: 'KC_SPACE', aliases: ['KC_SPC'], desc: 'Spacebar' },
    { code: 'KC_MINUS', aliases: ['KC_MINS'], desc: '- and _' },
    { code: 'KC_EQUAL', aliases: ['KC_EQL'], desc: '= and +' },
    { code: 'KC_LEFT_BRACKET', aliases: ['KC_LBRC'], desc: '[ and {' },
    { code: 'KC_RIGHT_BRACKET', aliases: ['KC_RBRC'], desc: '] and }' },
    { code: 'KC_BACKSLASH', aliases: ['KC_BSLS'], desc: '\\ and |' },
    { code: 'KC_NONUS_HASH', aliases: ['KC_NUHS'], desc: 'Non-US # and ~' },
    { code: 'KC_SEMICOLON', aliases: ['KC_SCLN'], desc: '; and :' },
    { code: 'KC_QUOTE', aliases: ['KC_QUOT'], desc: "' and \"" },
    { code: 'KC_GRAVE', aliases: ['KC_GRV'], desc: '` and ~' },
    { code: 'KC_COMMA', aliases: ['KC_COMM'], desc: ', and <' },
    { code: 'KC_DOT', aliases: [], desc: '. and >' },
    { code: 'KC_SLASH', aliases: ['KC_SLSH'], desc: '/ and ?' },
    { code: 'KC_NONUS_BACKSLASH', aliases: ['KC_NUBS'], desc: 'Non-US \\ and |' }
  ],
  locks: [
    { code: 'KC_CAPS_LOCK', aliases: ['KC_CAPS'], desc: 'Caps Lock' },
    { code: 'KC_SCROLL_LOCK', aliases: ['KC_SCRL', 'KC_BRMD'], desc: 'Scroll Lock, Brightness Down (macOS)' },
    { code: 'KC_NUM_LOCK', aliases: ['KC_NUM'], desc: 'Keypad Num Lock and Clear' },
    { code: 'KC_LOCKING_CAPS_LOCK', aliases: ['KC_LCAP'], desc: 'Locking Caps Lock' },
    { code: 'KC_LOCKING_NUM_LOCK', aliases: ['KC_LNUM'], desc: 'Locking Num Lock' },
    { code: 'KC_LOCKING_SCROLL_LOCK', aliases: ['KC_LSCR'], desc: 'Locking Scroll Lock' }
  ],
  modifiers: [
    { code: 'KC_LEFT_CTRL', aliases: ['KC_LCTL'], desc: 'Left Control' },
    { code: 'KC_LEFT_SHIFT', aliases: ['KC_LSFT'], desc: 'Left Shift' },
    { code: 'KC_LEFT_ALT', aliases: ['KC_LALT', 'KC_LOPT'], desc: 'Left Alt (Option)' },
    { code: 'KC_LEFT_GUI', aliases: ['KC_LGUI', 'KC_LCMD', 'KC_LWIN'], desc: 'Left GUI (Windows/Command/Super key)' },
    { code: 'KC_RIGHT_CTRL', aliases: ['KC_RCTL'], desc: 'Right Control' },
    { code: 'KC_RIGHT_SHIFT', aliases: ['KC_RSFT'], desc: 'Right Shift' },
    { code: 'KC_RIGHT_ALT', aliases: ['KC_RALT', 'KC_ROPT', 'KC_ALGR'], desc: 'Right Alt (Option/AltGr)' },
    { code: 'KC_RIGHT_GUI', aliases: ['KC_RGUI', 'KC_RCMD', 'KC_RWIN'], desc: 'Right GUI (Windows/Command/Super key)' }
  ],
  international: [
    { code: 'KC_INTERNATIONAL_1', aliases: ['KC_INT1'], desc: 'JIS \\ and _' },
    { code: 'KC_INTERNATIONAL_2', aliases: ['KC_INT2'], desc: 'JIS Katakana/Hiragana' },
    { code: 'KC_INTERNATIONAL_3', aliases: ['KC_INT3'], desc: 'JIS ¥ and |' },
    { code: 'KC_INTERNATIONAL_4', aliases: ['KC_INT4'], desc: 'JIS Henkan' },
    { code: 'KC_INTERNATIONAL_5', aliases: ['KC_INT5'], desc: 'JIS Muhenkan' },
    { code: 'KC_INTERNATIONAL_6', aliases: ['KC_INT6'], desc: 'JIS Numpad ,' },
    { code: 'KC_INTERNATIONAL_7', aliases: ['KC_INT7'], desc: 'International 7' },
    { code: 'KC_INTERNATIONAL_8', aliases: ['KC_INT8'], desc: 'International 8' },
    { code: 'KC_INTERNATIONAL_9', aliases: ['KC_INT9'], desc: 'International 9' },
    { code: 'KC_LANGUAGE_1', aliases: ['KC_LNG1'], desc: 'Hangul/English' },
    { code: 'KC_LANGUAGE_2', aliases: ['KC_LNG2'], desc: 'Hanja' },
    { code: 'KC_LANGUAGE_3', aliases: ['KC_LNG3'], desc: 'JIS Katakana' },
    { code: 'KC_LANGUAGE_4', aliases: ['KC_LNG4'], desc: 'JIS Hiragana' },
    { code: 'KC_LANGUAGE_5', aliases: ['KC_LNG5'], desc: 'JIS Zenkaku/Hankaku' },
    { code: 'KC_LANGUAGE_6', aliases: ['KC_LNG6'], desc: 'Language 6' },
    { code: 'KC_LANGUAGE_7', aliases: ['KC_LNG7'], desc: 'Language 7' },
    { code: 'KC_LANGUAGE_8', aliases: ['KC_LNG8'], desc: 'Language 8' },
    { code: 'KC_LANGUAGE_9', aliases: ['KC_LNG9'], desc: 'Language 9' }
  ],
  commands: [
    { code: 'KC_PRINT_SCREEN', aliases: ['KC_PSCR'], desc: 'Print Screen' },
    { code: 'KC_PAUSE', aliases: ['KC_PAUS', 'KC_BRK', 'KC_BRMU'], desc: 'Pause, Brightness Up (macOS)' },
    { code: 'KC_INSERT', aliases: ['KC_INS'], desc: 'Insert' },
    { code: 'KC_HOME', aliases: [], desc: 'Home' },
    { code: 'KC_PAGE_UP', aliases: ['KC_PGUP'], desc: 'Page Up' },
    { code: 'KC_DELETE', aliases: ['KC_DEL'], desc: 'Forward Delete' },
    { code: 'KC_END', aliases: [], desc: 'End' },
    { code: 'KC_PAGE_DOWN', aliases: ['KC_PGDN'], desc: 'Page Down' },
    { code: 'KC_RIGHT', aliases: ['KC_RGHT'], desc: 'Right Arrow' },
    { code: 'KC_LEFT', aliases: [], desc: 'Left Arrow' },
    { code: 'KC_DOWN', aliases: [], desc: 'Down Arrow' },
    { code: 'KC_UP', aliases: [], desc: 'Up Arrow' },
    { code: 'KC_APPLICATION', aliases: ['KC_APP'], desc: 'Application (Windows Context Menu Key)' },
    { code: 'KC_KB_POWER', aliases: [], desc: 'System Power' },
    { code: 'KC_EXECUTE', aliases: ['KC_EXEC'], desc: 'Execute' },
    { code: 'KC_HELP', aliases: [], desc: 'Help' },
    { code: 'KC_MENU', aliases: [], desc: 'Menu' },
    { code: 'KC_SELECT', aliases: ['KC_SLCT'], desc: 'Select' },
    { code: 'KC_STOP', aliases: [], desc: 'Stop' },
    { code: 'KC_AGAIN', aliases: ['KC_AGIN'], desc: 'Again' },
    { code: 'KC_UNDO', aliases: [], desc: 'Undo' },
    { code: 'KC_CUT', aliases: [], desc: 'Cut' },
    { code: 'KC_COPY', aliases: [], desc: 'Copy' },
    { code: 'KC_PASTE', aliases: ['KC_PSTE'], desc: 'Paste' },
    { code: 'KC_FIND', aliases: [], desc: 'Find' },
    { code: 'KC_KB_MUTE', aliases: [], desc: 'Mute' },
    { code: 'KC_KB_VOLUME_UP', aliases: [], desc: 'Volume Up' },
    { code: 'KC_KB_VOLUME_DOWN', aliases: [], desc: 'Volume Down' },
    { code: 'KC_ALTERNATE_ERASE', aliases: ['KC_ERAS'], desc: 'Alternate Erase' },
    { code: 'KC_SYSTEM_REQUEST', aliases: ['KC_SYRQ'], desc: 'SysReq/Attention' },
    { code: 'KC_CANCEL', aliases: ['KC_CNCL'], desc: 'Cancel' },
    { code: 'KC_CLEAR', aliases: ['KC_CLR'], desc: 'Clear' },
    { code: 'KC_PRIOR', aliases: ['KC_PRIR'], desc: 'Prior' },
    { code: 'KC_RETURN', aliases: ['KC_RETN'], desc: 'Return' },
    { code: 'KC_SEPARATOR', aliases: ['KC_SEPR'], desc: 'Separator' },
    { code: 'KC_OUT', aliases: [], desc: 'Out' },
    { code: 'KC_OPER', aliases: [], desc: 'Oper' },
    { code: 'KC_CLEAR_AGAIN', aliases: ['KC_CLAG'], desc: 'Clear/Again' },
    { code: 'KC_CRSEL', aliases: ['KC_CRSL'], desc: 'CrSel/Props' },
    { code: 'KC_EXSEL', aliases: ['KC_EXSL'], desc: 'ExSel' }
  ],
  media: [
    { code: 'KC_SYSTEM_POWER', aliases: ['KC_PWR'], desc: 'System Power Down' },
    { code: 'KC_SYSTEM_SLEEP', aliases: ['KC_SLEP'], desc: 'System Sleep' },
    { code: 'KC_SYSTEM_WAKE', aliases: ['KC_WAKE'], desc: 'System Wake' },
    { code: 'KC_AUDIO_MUTE', aliases: ['KC_MUTE'], desc: 'Mute' },
    { code: 'KC_AUDIO_VOL_UP', aliases: ['KC_VOLU'], desc: 'Volume Up' },
    { code: 'KC_AUDIO_VOL_DOWN', aliases: ['KC_VOLD'], desc: 'Volume Down' },
    { code: 'KC_MEDIA_NEXT_TRACK', aliases: ['KC_MNXT'], desc: 'Next Track' },
    { code: 'KC_MEDIA_PREV_TRACK', aliases: ['KC_MPRV'], desc: 'Previous Track' },
    { code: 'KC_MEDIA_STOP', aliases: ['KC_MSTP'], desc: 'Stop Track' },
    { code: 'KC_MEDIA_PLAY_PAUSE', aliases: ['KC_MPLY'], desc: 'Play/Pause Track' },
    { code: 'KC_MEDIA_SELECT', aliases: ['KC_MSEL'], desc: 'Launch Media Player' },
    { code: 'KC_MEDIA_EJECT', aliases: ['KC_EJCT'], desc: 'Eject' },
    { code: 'KC_MAIL', aliases: [], desc: 'Launch Mail' },
    { code: 'KC_CALCULATOR', aliases: ['KC_CALC'], desc: 'Launch Calculator' },
    { code: 'KC_MY_COMPUTER', aliases: ['KC_MYCM'], desc: 'Launch My Computer' },
    { code: 'KC_WWW_SEARCH', aliases: ['KC_WSCH'], desc: 'Browser Search' },
    { code: 'KC_WWW_HOME', aliases: ['KC_WHOM'], desc: 'Browser Home' },
    { code: 'KC_WWW_BACK', aliases: ['KC_WBAK'], desc: 'Browser Back' },
    { code: 'KC_WWW_FORWARD', aliases: ['KC_WFWD'], desc: 'Browser Forward' },
    { code: 'KC_WWW_STOP', aliases: ['KC_WSTP'], desc: 'Browser Stop' },
    { code: 'KC_WWW_REFRESH', aliases: ['KC_WREF'], desc: 'Browser Refresh' },
    { code: 'KC_WWW_FAVORITES', aliases: ['KC_WFAV'], desc: 'Browser Favorites' },
    { code: 'KC_MEDIA_FAST_FORWARD', aliases: ['KC_MFFD'], desc: 'Fast Forward' },
    { code: 'KC_MEDIA_REWIND', aliases: ['KC_MRWD'], desc: 'Rewind' },
    { code: 'KC_BRIGHTNESS_UP', aliases: ['KC_BRIU'], desc: 'Brightness Up' },
    { code: 'KC_BRIGHTNESS_DOWN', aliases: ['KC_BRID'], desc: 'Brightness Down' },
    { code: 'KC_CONTROL_PANEL', aliases: ['KC_CPNL'], desc: 'Open Control Panel' },
    { code: 'KC_ASSISTANT', aliases: ['KC_ASST'], desc: 'Launch Assistant' },
    { code: 'KC_MISSION_CONTROL', aliases: ['KC_MCTL'], desc: 'Open Mission Control' },
    { code: 'KC_LAUNCHPAD', aliases: ['KC_LPAD'], desc: 'Open Launchpad' }
  ],
  keypad: [
    { code: 'KC_KP_SLASH', aliases: ['KC_PSLS'], desc: 'Keypad /' },
    { code: 'KC_KP_ASTERISK', aliases: ['KC_PAST'], desc: 'Keypad *' },
    { code: 'KC_KP_MINUS', aliases: ['KC_PMNS'], desc: 'Keypad -' },
    { code: 'KC_KP_PLUS', aliases: ['KC_PPLS'], desc: 'Keypad +' },
    { code: 'KC_KP_ENTER', aliases: ['KC_PENT'], desc: 'Keypad Enter' },
    { code: 'KC_KP_1', aliases: ['KC_P1'], desc: 'Keypad 1 and End' },
    { code: 'KC_KP_2', aliases: ['KC_P2'], desc: 'Keypad 2 and Down Arrow' },
    { code: 'KC_KP_3', aliases: ['KC_P3'], desc: 'Keypad 3 and Page Down' },
    { code: 'KC_KP_4', aliases: ['KC_P4'], desc: 'Keypad 4 and Left Arrow' },
    { code: 'KC_KP_5', aliases: ['KC_P5'], desc: 'Keypad 5' },
    { code: 'KC_KP_6', aliases: ['KC_P6'], desc: 'Keypad 6 and Right Arrow' },
    { code: 'KC_KP_7', aliases: ['KC_P7'], desc: 'Keypad 7 and Home' },
    { code: 'KC_KP_8', aliases: ['KC_P8'], desc: 'Keypad 8 and Up Arrow' },
    { code: 'KC_KP_9', aliases: ['KC_P9'], desc: 'Keypad 9 and Page Up' },
    { code: 'KC_KP_0', aliases: ['KC_P0'], desc: 'Keypad 0 and Insert' },
    { code: 'KC_KP_DOT', aliases: ['KC_PDOT'], desc: 'Keypad . and Delete' },
    { code: 'KC_KP_EQUAL', aliases: ['KC_PEQL'], desc: 'Keypad =' },
    { code: 'KC_KP_COMMA', aliases: ['KC_PCMM'], desc: 'Keypad ,' },
    { code: 'KC_KP_EQUAL_AS400', aliases: [], desc: 'Keypad = on AS/400 keyboards' }
  ],
  layers: [
    { code: 'DF(0)', aliases: [], desc: 'Switch default layer to 0' },
    { code: 'MO(0)', aliases: [], desc: 'Momentary activate layer 0' },
    { code: 'TG(0)', aliases: [], desc: 'Toggle layer 0' },
    { code: 'TO(0)', aliases: [], desc: 'Activate layer 0 and deactivate others' },
    { code: 'DF(1)', aliases: [], desc: 'Switch default layer to 1' },
    { code: 'MO(1)', aliases: [], desc: 'Momentary activate layer 1' },
    { code: 'TG(1)', aliases: [], desc: 'Toggle layer 1' },
    { code: 'TO(1)', aliases: [], desc: 'Activate layer 1 and deactivate others' },
    { code: 'DF(2)', aliases: [], desc: 'Switch default layer to 2' },
    { code: 'MO(2)', aliases: [], desc: 'Momentary activate layer 2' },
    { code: 'TG(2)', aliases: [], desc: 'Toggle layer 2' },
    { code: 'TO(2)', aliases: [], desc: 'Activate layer 2 and deactivate others' },
    { code: 'DF(3)', aliases: [], desc: 'Switch default layer to 3' },
    { code: 'MO(3)', aliases: [], desc: 'Momentary activate layer 3' },
    { code: 'TG(3)', aliases: [], desc: 'Toggle layer 3' },
    { code: 'TO(3)', aliases: [], desc: 'Activate layer 3 and deactivate others' },
    { code: 'DF(4)', aliases: [], desc: 'Switch default layer to 4' },
    { code: 'MO(4)', aliases: [], desc: 'Momentary activate layer 4' },
    { code: 'TG(4)', aliases: [], desc: 'Toggle layer 4' },
    { code: 'TO(4)', aliases: [], desc: 'Activate layer 4 and deactivate others' },
    { code: 'DF(5)', aliases: [], desc: 'Switch default layer to 5' },
    { code: 'MO(5)', aliases: [], desc: 'Momentary activate layer 5' },
    { code: 'TG(5)', aliases: [], desc: 'Toggle layer 5' },
    { code: 'TO(5)', aliases: [], desc: 'Activate layer 5 and deactivate others' },
    { code: 'LM(1, MOD_LCTL)', aliases: [], desc: 'Momentary layer 1 with Left Ctrl' },
    { code: 'LT(1, KC_SPC)', aliases: [], desc: 'Layer-tap: hold for layer 1, tap for Space' },
    { code: 'OSL(1)', aliases: [], desc: 'One-shot layer 1' },
    { code: 'TT(1)', aliases: [], desc: 'Layer tap-toggle' }
  ],
  mouse: [
    { code: 'QK_MOUSE_CURSOR_UP', aliases: ['MS_UP'], desc: 'Mouse cursor up' },
    { code: 'QK_MOUSE_CURSOR_DOWN', aliases: ['MS_DOWN'], desc: 'Mouse cursor down' },
    { code: 'QK_MOUSE_CURSOR_LEFT', aliases: ['MS_LEFT'], desc: 'Mouse cursor left' },
    { code: 'QK_MOUSE_CURSOR_RIGHT', aliases: ['MS_RGHT'], desc: 'Mouse cursor right' },
    { code: 'QK_MOUSE_BUTTON_1', aliases: ['MS_BTN1'], desc: 'Mouse button 1' },
    { code: 'QK_MOUSE_BUTTON_2', aliases: ['MS_BTN2'], desc: 'Mouse button 2' },
    { code: 'QK_MOUSE_BUTTON_3', aliases: ['MS_BTN3'], desc: 'Mouse button 3' },
    { code: 'QK_MOUSE_WHEEL_UP', aliases: ['MS_WHLU'], desc: 'Mouse wheel up' },
    { code: 'QK_MOUSE_WHEEL_DOWN', aliases: ['MS_WHLD'], desc: 'Mouse wheel down' },
    { code: 'QK_MOUSE_WHEEL_LEFT', aliases: ['MS_WHLL'], desc: 'Mouse wheel left' },
    { code: 'QK_MOUSE_WHEEL_RIGHT', aliases: ['MS_WHLR'], desc: 'Mouse wheel right' },
    { code: 'QK_MOUSE_ACCELERATION_0', aliases: ['MS_ACL0'], desc: 'Set mouse acceleration to 0' },
    { code: 'QK_MOUSE_ACCELERATION_1', aliases: ['MS_ACL1'], desc: 'Set mouse acceleration to 1' },
    { code: 'QK_MOUSE_ACCELERATION_2', aliases: ['MS_ACL2'], desc: 'Set mouse acceleration to 2' }
  ],
  modtap: [
    { code: 'LCTL_T(KC_A)', aliases: [], desc: 'Mod-tap: hold for Left Ctrl, tap for A' },
    { code: 'LSFT_T(KC_S)', aliases: [], desc: 'Mod-tap: hold for Left Shift, tap for S' },
    { code: 'LALT_T(KC_D)', aliases: [], desc: 'Mod-tap: hold for Left Alt, tap for D' },
    { code: 'LGUI_T(KC_F)', aliases: [], desc: 'Mod-tap: hold for Left GUI, tap for F' },
    { code: 'RCTL_T(KC_J)', aliases: [], desc: 'Mod-tap: hold for Right Ctrl, tap for J' },
    { code: 'RSFT_T(KC_K)', aliases: [], desc: 'Mod-tap: hold for Right Shift, tap for K' },
    { code: 'RALT_T(KC_L)', aliases: [], desc: 'Mod-tap: hold for Right Alt, tap for L' },
    { code: 'RGUI_T(KC_SCLN)', aliases: [], desc: 'Mod-tap: hold for Right GUI, tap for ;' }
  ],
  oneshot: [
    { code: 'OSM(MOD_LSFT)', aliases: [], desc: 'One-shot Left Shift' },
    { code: 'OSM(MOD_LCTL)', aliases: [], desc: 'One-shot Left Ctrl' },
    { code: 'OSM(MOD_LALT)', aliases: [], desc: 'One-shot Left Alt' },
    { code: 'OSM(MOD_LGUI)', aliases: [], desc: 'One-shot Left GUI' }
  ],
  capsword: [
    { code: 'CW_TOGG', aliases: [], desc: 'Toggle Caps Word' }
  ],
  audio: [
    { code: 'AU_ON', aliases: [], desc: 'Audio on' },
    { code: 'AU_OFF', aliases: [], desc: 'Audio off' },
    { code: 'AU_TOGG', aliases: [], desc: 'Audio toggle' }
  ],
  special: [
    { code: 'KC_NO', aliases: ['XXXXXXX'], desc: 'Ignore this key (NOOP)' },
    { code: 'KC_TRANSPARENT', aliases: ['KC_TRNS', '_______'], desc: 'Use the next lowest non-transparent key' },
    { code: 'QK_BOOT', aliases: [], desc: 'Enter bootloader' },
    { code: 'QK_RBT', aliases: [], desc: 'Reset keyboard' }
  ]
};

// Flatten for search
const allKeycodes = [];
for (const category in keycodes) {
  keycodes[category].forEach(kc => {
    allKeycodes.push(kc);
    kc.aliases.forEach(alias => allKeycodes.push({ code: alias, desc: kc.desc, aliases: [] }));
  });
}